# Generated by Django 2.0.13 on 2020-11-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('enum', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('attendance', models.IntegerField()),
            ],
            options={
                'db_table': 'Attendance',
                'managed': False,
            },
        ),
    ]
